#!/bin/sh

if test -z "$1"; then
    echo "usage: git fixup-changelogs BASE-REVISION" 1>&2
    exit 1
fi

dir=$(git rev-parse --git-dir)
base_rev="$1"

GIT_EDITOR='perl -pi -e s/pick/edit/' git rebase -i "$base_rev"

while test -f $dir/rebase-merge/interactive; do
    git simple-fixup
    GIT_EDITOR=true git commit -a --amend
    GIT_EDITOR=true git rebase --continue
done

exit 0
