#!/bin/sh

if test -z "$1"; then
    base_rev=@{u}
else
    base_rev="$1"
fi

dir=$(git rev-parse --git-dir)

GIT_EDITOR='perl -pi -e s/pick/edit/' git rebase -i "$base_rev"

date=$(date)
while test -f $dir/rebase-merge/interactive; do
    git simple-fixup
    GIT_EDITOR=true git commit -a --amend --date="$date"
    GIT_EDITOR=true git rebase --continue
done

exit 0
