#!/bin/sh

today=$(date +%Y-%m-%d)
top=$(git rev-parse --show-cdup)
git log -1 --pretty=format: --name-only $GIT_COMMIT |
grep ChangeLog |
while read clfile; do
    echo "Rewriting $clfile..."
    sed -i "1 s/^[0-9-]*/$today/" $top/$clfile
done
